image: docker:stable

services:
  - docker:dind

stages:
  - package
  - tag

docker-build:
  stage: package
  tags:
    - gitlab-org-docker
  script:
    - docker build
      --build-arg DOCKER_NAME=$CI_DOCKER_NAME
      -t $CI_DOCKER_SERVER/$CI_DOCKER_REGISTRY/$CI_DOCKER_NAME:latest .
    - docker login -u $CI_DOCKER_USER -p $CI_DOCKER_PASSWORD $CI_DOCKER_SERVER
    - docker push $CI_DOCKER_SERVER/$CI_DOCKER_REGISTRY/$CI_DOCKER_NAME:latest
  only:
    - development
    - test
    - main
  when: manual

docker-tag:
  stage: tag
  tags:
    - gitlab-org-docker
  script:
    - docker login -u $CI_DOCKER_USER -p $CI_DOCKER_PASSWORD $CI_DOCKER_SERVER
    - docker pull $CI_DOCKER_SERVER/$CI_DOCKER_REGISTRY/$CI_DOCKER_NAME:latest
    - docker tag
      $CI_DOCKER_SERVER/$CI_DOCKER_REGISTRY/$CI_DOCKER_NAME:latest
      $CI_DOCKER_SERVER/$CI_DOCKER_REGISTRY/$CI_DOCKER_NAME:${CI_COMMIT_REF_NAME}
    - docker push $CI_DOCKER_SERVER/$CI_DOCKER_REGISTRY/$CI_DOCKER_NAME:${CI_COMMIT_REF_NAME}
  only:
    - development
    - test
  when: manual

docker-tag-main:
  stage: tag
  tags:
    - gitlab-org-docker
  script:
    - docker login -u $CI_DOCKER_USER -p $CI_DOCKER_PASSWORD $CI_DOCKER_SERVER
    - docker pull $CI_DOCKER_SERVER/$CI_DOCKER_REGISTRY/$CI_DOCKER_NAME:latest
    - docker tag
      $CI_DOCKER_SERVER/$CI_DOCKER_REGISTRY/$CI_DOCKER_NAME:latest
      $CI_DOCKER_SERVER/$CI_DOCKER_REGISTRY/$CI_DOCKER_NAME:master
    - docker push $CI_DOCKER_SERVER/$CI_DOCKER_REGISTRY/$CI_DOCKER_NAME:master
  only:
    - main
  when: manual
