"""
Application constants and configuration values.
"""

# API Configuration
DEFAULT_PORT = 5000
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_RATE_LIMIT = 20
DEFAULT_API_VERSION = "2024-08-01-preview"

# Model Configuration
DEFAULT_EMBEDDING_MODEL = "text-embedding-3-large"
DEFAULT_CHAT_MODEL = "gpt-4.1-mini"
DEFAULT_TEMPERATURE = 0.0
DEFAULT_TIMEOUT = 60


# Model Types
CHAT_TYPE = "chat"
COMPLETIONS_TYPE = "completions"
EMBEDDING_TYPE = "embedding"

# Health Check
HEALTH_STATUS_HEALTHY = "healthy"
HEALTH_STATUS_UNHEALTHY = "unhealthy"

# Pagination
DEFAULT_LIMIT = 100
DEFAULT_PAGE = 1

# Cache
DEFAULT_CACHE_TTL = 60

# Recursion
DEFAULT_RECURSION_LIMIT = 1

# Document Processing
DEFAULT_CHUNK_SIZE = 5000
DEFAULT_CHUNK_OVERLAP = 250
DEFAULT_MAX_CONTENT_LENGTH = 5000

# Logging
DEFAULT_LOG_MAX_FILE_SIZE_MB = 10
DEFAULT_LOG_BACKUP_COUNT = 5
