import os


class Config:
    LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
    PORT = os.getenv("PORT", 5000)
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
    AZURE_BASE_URL = os.getenv("AZURE_BASE_URL")
    AZURE_DEPLOYMENT_NAME = os.getenv("AZURE_DEPLOYMENT_NAME")
    AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
    LANGCHAIN_TRACING_V2 = os.getenv("LANGCHAIN_TRACING_V2")
    LANGCHAIN_PROJECT = os.getenv("LANGCHAIN_PROJECT")
    LANGCHAIN_ENDPOINT = os.getenv("LANGCHAIN_ENDPOINT")
    LANGCHAIN_API_KEY = os.getenv("LANGCHAIN_API_KEY")
    SERPAPI_API_KEY = os.getenv("SERPAPI_API_KEY")
    HISTORY_CLEAR_SCHEDULE_IN_MINUTE = os.getenv("HISTORY_CLEAR_SCHEDULE_IN_MINUTE", 60)
